version: '2'
services:
  app:
    container_name: node
    restart: always
    build: .
    ports:
      - '2000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27117:27017'
