version: '2'
services:
  app:
    restart: always
    build: .
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27117:27017'
  reverseproxy:
     container_name: xbalancer
     image: nginx-reverseproxy
     links: 
        - redis
     ports: 
        - "9999:8080"
  redis:
      image: redis
      container_name: xredis_server
